gh_blog_home:
    pattern:  /
    defaults: { _controller: "GhBlogBundle:Post:list" }

gh_blog_about:
    pattern:  /about
    defaults: { _controller: "GhBlogBundle:Index:about" }

gh_blog_post:
    pattern:  /post/{slug}
    defaults: { _controller: "GhBlogBundle:Post:show" }